from __future__ import annotations

from collections import Counter
from pathlib import Path

from .constants import (
    DEFAULT_PLATFORM_SUFFIXES,
    DEFAULT_PREFIXES,
    LANGUAGES,
    MISSING_REPORT_SUFFIX,
)
from .models import DmpScanResult, SuffixCounts


def merge_suffix_counts(*maps: SuffixCounts) -> SuffixCounts:
    merged: SuffixCounts = {}
    for suffix_map in maps:
        for extension, versions in suffix_map.items():
            merged.setdefault(extension, Counter()).update(versions)
    return merged


def versions_as_sorted_lists(suffix_counts: SuffixCounts) -> dict[str, list[int]]:
    return {
        extension: sorted(versions)
        for extension, versions in sorted(suffix_counts.items())
        if versions
    }


def format_string_array(values: list[str], indent: str = "    ") -> str:
    if not values:
        return "[]"
    body = ",\n".join(f'{indent}"{value}"' for value in values)
    return f"[\n{body},\n]"


def quote_toml_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def format_suffix_line(extension: str, versions: list[int]) -> str:
    return f"{extension} = [{', '.join(str(version) for version in versions)}]"


def build_config_text(
    suffix_counts: SuffixCounts,
    languages: list[str] | None = None,
    prefixes: list[str] | None = None,
    platform_suffixes: list[str] | None = None,
    use_builtin_suffix_map: bool = False,
) -> str:
    languages = languages or LANGUAGES
    prefixes = prefixes or DEFAULT_PREFIXES
    platform_suffixes = platform_suffixes or DEFAULT_PLATFORM_SUFFIXES

    lines = [
        "# Generated by re-file-hash-exporter",
        "",
        f"languages = {format_string_array(languages)}",
        f"prefixes = [{', '.join(quote_toml_string(p) for p in prefixes)}]",
        f"platform_suffixes = [{', '.join(quote_toml_string(p) for p in platform_suffixes)}]",
        f"use_builtin_suffix_map = {'true' if use_builtin_suffix_map else 'false'}",
        "",
        "[suffix_map]",
    ]

    for extension, versions in versions_as_sorted_lists(suffix_counts).items():
        lines.append(format_suffix_line(extension, versions))

    return "\n".join(lines) + "\n"


def write_config(output_path: Path, suffix_counts: SuffixCounts) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(build_config_text(suffix_counts), encoding="utf-8", newline="\n")


def default_missing_report_path(output_path: Path) -> Path:
    return output_path.with_name(f"{output_path.stem}{MISSING_REPORT_SUFFIX}")


def build_missing_report(scan: DmpScanResult) -> str:
    lines = [
        "# Missing resource suffix versions",
        "",
        "DMP files:",
    ]
    lines.extend(f"- {path}" for path in scan.dmp_files)
    lines.extend(
        [
            "",
            "These paths were seen as raw `name.ext` strings without a numeric",
            "`.version` suffix in the DMP. They can be used by the optional",
            "brute-force step.",
            "",
        ]
    )

    if not scan.unversioned_paths:
        lines.append("No unversioned resource paths were found.")
        return "\n".join(lines) + "\n"

    lines.extend(
        [
            f"Total occurrences: {scan.unversioned_occurrence_count}",
            f"Unique paths: {scan.unversioned_unique_path_count}",
            f"Extensions: {scan.unversioned_extension_count}",
            "",
            "extension\toccurrences\tunique_paths",
        ]
    )
    for extension, paths in sorted(scan.unversioned_paths.items()):
        lines.append(f"{extension}\t{sum(paths.values())}\t{len(paths)}")

    lines.extend(["", "Detailed missing paths:", ""])
    for extension, paths in sorted(scan.unversioned_paths.items()):
        lines.append(f"[{extension}] occurrences={sum(paths.values())} unique_paths={len(paths)}")
        for path, count in paths.most_common():
            lines.append(f"{count}\t{path}")
        lines.append("")

    return "\n".join(lines)


def write_missing_report(output_path: Path, scan: DmpScanResult) -> Path:
    report_path = default_missing_report_path(output_path)
    report_path.write_text(build_missing_report(scan), encoding="utf-8", newline="\n")
    return report_path
